parser = clink.arg.new_parser

local goals = parser(
	{
		"-am",
		"-amd",
		"-B",
		"-C",
		"-c",
		"-cpu",
		"-D",
		"-e",
		"-emp",
		"-ep",
		"-f",
		"-fae",
		"-ff",
		"-fn",
		"-gs",
		"-h",
		"-l",
		"-N",
		"-npr",
		"-npu",
		"-nsu",
		"-o",
		"-P",
		"-pl",
		"-q",
		"-rf",
		"-s",
		"-T",
		"-t",
		"-U",
		"-up",
		"-V",
		"-v",
		"-X", 
		
		"--also-make",
		"--also-make-dependents",
		"--batch-mode",
		"--strict-checksums",
		"--lax-checksums",
		"--check-plugin-updates",
		"--define",
		"--errors",
		"--encrypt-master-password",
		"--encrypt-password",
		"--file",
		"--fail-at-end",
		"--fail-fast",
		"--fail-never",
		"--global-settings",
		"--help",
		"--log-file",
		"--non-recursive",
		"--no-plugin-registry",
		"--no-plugin-updates",
		"--no-snapshot-updates",
		"--offline",
		"--activate-profiles",
		"--projects",
		"--quiet",
		"--resume-from",
		"--settings",
		"--threads",
		"--toolchains",
		"--update-snapshots",
		"--update-plugins",
		"--show-version",
		"--version",
		"--debug",
		
		"pre-clean",
		"clean",
		"post-clean", 
		
		"install", 
		"validate",
		"initialize",
		"generate-sources",
		"process-sources",
		"generate-resources",
		"process-resources",
		"compile",
		"process-classes",
		"generate-test-sources",
		"process-test-sources",
		"generate-test-resources",
		"process-test-resources",
		"test-compile",
		"process-test-classes",
		"test",
		"prepare-package",
		"package",
		"pre-integration-test",
		"integration-test",
		"post-integration-test",
		"verify",
		"install",
		"deploy",
		
		"pre-site",
		"site",
		"post-site",
		"site-deploy",
		
		"help:active-profiles",
		"help:all-profiles",
		"help:describe",
		"help:effective-pom",
		"help:effective-settings",
		"help:evaluate",
		"help:expressions",
		"help:help",
		"help:system",
		
		"exec:exec",
		
		"wildfly:deploy",
		
		"-DskipTests"
	}
):loop(1)

clink.arg.register_parser("mvn", goals)